# Generated by Django 3.0.5 on 2020-05-05 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('ruc', models.CharField(blank=True, max_length=15, null=True)),
                ('rznsocial', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=200, null=True)),
                ('detalle', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
                ('st_sgestion', models.CharField(default='EMITIDA', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id_moneda', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('abreviatura', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'moneda',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('serie', models.CharField(blank=True, max_length=4, null=True)),
                ('numero', models.CharField(blank=True, max_length=8, null=True)),
                ('fec_emision', models.DateTimeField(blank=True, null=True)),
                ('id_usuario', models.IntegerField(null=True)),
                ('tipo_doc_iden', models.CharField(blank=True, max_length=1, null=True)),
                ('num_doc_iden', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=200, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('entrega_domicilio', models.BooleanField(default=False)),
                ('costo_entrega', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('st_pedido', models.CharField(blank=True, max_length=200, null=True)),
                ('cancelado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.Empresa')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('imagen', models.ImageField(default='static/imagen_no_disponible.png', upload_to='producto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.Categoria')),
                ('moneda', models.ForeignKey(blank=True, db_column='id_moneda', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.Moneda')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('id_ubigeo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'ubigeo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_doc_ident', models.CharField(choices=[('1', 'DNI'), ('4', 'CARNET DE EXTRANJERIA'), ('6', 'RUC'), ('7', 'PASAPORTE'), ('11', 'PART. DE NACIMIENTO-IDENTIDAD'), ('0', 'OTROS')], default='0', max_length=2)),
                ('num_doc_ident', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen', models.ImageField(default='static/usuario.jpg.png', upload_to='usuario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('ubigeo', models.ForeignKey(db_column='id_ubigeo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.Ubigeo')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Productodetalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(blank=True, max_length=200, null=True)),
                ('valor', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.Producto')),
            ],
            options={
                'db_table': 'productodetalle',
            },
        ),
        migrations.CreateModel(
            name='Pedidodetalle',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('coproducto', models.CharField(blank=True, max_length=15, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.Pedido')),
                ('producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.Producto')),
            ],
            options={
                'db_table': 'pedidodetalle',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='ubigeo',
            field=models.ForeignKey(blank=True, db_column='id_ubigeo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.Ubigeo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ubigeo',
            field=models.ForeignKey(blank=True, db_column='id_ubigeo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.Ubigeo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.Usuario'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.Empresa'),
        ),
    ]
