# Generated by Django 3.0.5 on 2020-04-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_producto_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='detalle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
