# Generated by Django 3.0.5 on 2020-05-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20200511_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_doc_iden',
            field=models.CharField(choices=[('01', 'DNI'), ('04', 'CARNET DE EXTRANJERIA'), ('06', 'RUC'), ('07', 'PASAPORTE'), ('11', 'PART. DE NACIMIENTO-IDENTIDAD'), ('00', 'OTROS')], default='00', max_length=2),
        ),
    ]
