# Generated by Django 3.0.5 on 2020-04-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20200425_1056'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='nombre',
        ),
    ]
