# Generated by Django 3.0.5 on 2020-04-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20200425_1057'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
