# Generated by Django 3.0.5 on 2020-04-25 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20200425_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ubigeo',
            field=models.ForeignKey(db_column='id_ubigeo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.Ubigeo'),
        ),
    ]
