# Generated by Django 3.0.5 on 2020-04-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20200425_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id_usuario',
            field=models.IntegerField(null=True),
        ),
    ]
